<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <ProjectReference Include="..\PilotCapture.Domain\PilotCapture.Domain.csproj" />
    <ProjectReference Include="..\PilotCapture.Application\PilotCapture.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Persistence\Migrations\*.sql" />
  </ItemGroup>
</Project>
